name: Package and Release Addon

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and Upload to CurseForge
        uses: BigWigsMods/packager@v2
        with:
          args: "-v -g retail" # -v attiva il log dettagliato, -g retail aiuta il fetch
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}